version: '3.3'

services:
  mybatis-mysql:
    imaage: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mybatis
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123456
  demo-springboot-docker:
    image: tomoyadeng/demo-springboot-docker
    depends_on:
      - mybatis-mysql
    ports:
      - 8088:8080
    environment:
      - DATABASE_HOST=mybatis-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=mybatis
      - DATABASE_PORT=3306
